/**
 * Span Attribute Cache — lightweight in-process K-V store that captures a
 * snapshot of every span's attributes just before the span is ended.
 */

// ── Types ────────────────────────────────────────────────────────────

export type SpanAttributeValue = string | number | boolean;

/**
 * Immutable snapshot of a span's key identifiers and attributes,
 * captured just before `span.end()` is called.
 */
export interface SpanRecord {
  traceId: string;
  spanId: string;
  spanName: string;
  
  spanKind: string;
  /** openclaw.session.key — the runtime correlation key */
  sessionKey: string;
  /** session.id UUID generated by session-lifecycle.ts, if available */
  sessionId?: string;
  /** Full attribute snapshot at the moment span.end() was called */
  attributes: Record<string, SpanAttributeValue>;
  recordedAt: number;
}

// ── Configuration ────────────────────────────────────────────────────

/** Records older than this are removed during periodic stale sweeps. */
const DEFAULT_MAX_AGE_MS = 30 * 60 * 1_000; // 30 minutes

/** Maximum records stored per session key (oldest are evicted first). */
const DEFAULT_MAX_RECORDS_PER_SESSION = 500;

/** How often the background stale-sweep runs. */
const DEFAULT_FLUSH_INTERVAL_MS = 60_000; // 1 minute

// ── Internal state ───────────────────────────────────────────────────

/** session UUID (from session-lifecycle) → records */
const bySession = new Map<string, SpanRecord[]>();

/** W3C traceId → records */
const byTrace = new Map<string, SpanRecord[]>();

/** openclaw.session.key (runtime key) → records */
const bySessionKey = new Map<string, SpanRecord[]>();

let flushTimer: ReturnType<typeof setInterval> | null = null;
let maxAgeMs = DEFAULT_MAX_AGE_MS;
let maxRecordsPerSession = DEFAULT_MAX_RECORDS_PER_SESSION;
let loggerRef: any = null;
let cacheEnabled = false;

// ── Helpers ──────────────────────────────────────────────────────────

function appendCapped(
  map: Map<string, SpanRecord[]>,
  key: string,
  record: SpanRecord,
  cap: number
): void {
  const list = map.get(key);
  if (!list) {
    map.set(key, [record]);
    return;
  }
  list.push(record);
  if (list.length > cap) {
    // Evict oldest entries from the front
    list.splice(0, list.length - cap);
  }
}

// ── Public API ───────────────────────────────────────────────────────

/**
 * Start the background stale-eviction timer.
 */
export function startSpanCache(options?: {
  enabled?: boolean;
  logger?: any;
  maxAgeMs?: number;
  maxRecordsPerSession?: number;
  flushIntervalMs?: number;
}): void {
  if (options?.logger) loggerRef = options.logger;
  if (options?.maxAgeMs) maxAgeMs = options.maxAgeMs;
  if (options?.maxRecordsPerSession) maxRecordsPerSession = options.maxRecordsPerSession;

  cacheEnabled = options?.enabled === true;

  if (!cacheEnabled) {
    stopSpanCache();
    loggerRef?.debug?.("[otel:span-cache] Disabled by config");
    return;
  }

  if (flushTimer) return; // already running

  const intervalMs = options?.flushIntervalMs ?? DEFAULT_FLUSH_INTERVAL_MS;
  flushTimer = setInterval(() => sweepStale(), intervalMs);

  loggerRef?.debug?.(
    `[otel:span-cache] Started (maxAge=${maxAgeMs}ms, cap=${maxRecordsPerSession}, interval=${intervalMs}ms)`
  );
}

/**
 * Stop the background eviction timer and clear all cached records.
 */
export function stopSpanCache(): void {
  if (flushTimer) {
    clearInterval(flushTimer);
    flushTimer = null;
  }
  cacheEnabled = false;
  bySession.clear();
  byTrace.clear();
  bySessionKey.clear();
  loggerRef?.debug?.("[otel:span-cache] Stopped and cleared");
}

/**
 * Record a span's attribute snapshot. Call this just before `span.end()`.
 *
 */
export function recordSpan(record: SpanRecord): void {
  if (!cacheEnabled) {
    return;
  }

  const { traceId, sessionKey, sessionId } = record;

  appendCapped(bySessionKey, sessionKey, record, maxRecordsPerSession);

  if (sessionId) {
    appendCapped(bySession, sessionId, record, maxRecordsPerSession);
  }

  appendCapped(byTrace, traceId, record, maxRecordsPerSession);
}

// ── Lookup API ───────────────────────────────────────────────────────

/**
 * Return all cached records for a given W3C trace ID.
 * Returns a snapshot copy so callers cannot mutate internal state.
 */
export function getByTrace(traceId: string): SpanRecord[] {
  return [...(byTrace.get(traceId) ?? [])];
}

/**
 * Return all cached records for a session UUID
 * (generated by session-lifecycle.ts, exposed as `session.id` on spans).
 */
export function getBySession(sessionId: string): SpanRecord[] {
  return [...(bySession.get(sessionId) ?? [])];
}

/**
 * Return all cached records for an openclaw runtime session key
 * (the correlation key that appears as `openclaw.session.key` on spans).
 */
export function getBySessionKey(sessionKey: string): SpanRecord[] {
  return [...(bySessionKey.get(sessionKey) ?? [])];
}

/**
 * Return a summary count of how many records are currently cached.
 */
export function getCacheStats(): { sessions: number; traces: number; sessionKeys: number } {
  return {
    sessions: bySession.size,
    traces: byTrace.size,
    sessionKeys: bySessionKey.size,
  };
}

// ── Flush API ─────────────────────────────────────────────────────────

/**
 * Flush (remove) all cached records for a runtime session key and its
 * associated session UUID. Call this when a session ends.
 */
export function flushBySessionKey(sessionKey: string): void {
  if (!cacheEnabled) {
    return;
  }

  const records = bySessionKey.get(sessionKey);
  if (!records) return;

  // Collect trace IDs and session UUIDs touched by this session so we
  // can prune those indices too.
  const traceIds = new Set<string>();
  const sessionIds = new Set<string>();

  for (const r of records) {
    traceIds.add(r.traceId);
    if (r.sessionId) sessionIds.add(r.sessionId);
  }

  bySessionKey.delete(sessionKey);

  for (const sid of sessionIds) {
    bySession.delete(sid);
  }

  // Only remove trace entries that belong exclusively to this session.
  // A trace may span multiple session keys (e.g. spawned subagent inherits
  // the parent trace), so we check each record before removing.
  for (const tid of traceIds) {
    const traceRecords = byTrace.get(tid);
    if (!traceRecords) continue;
    const remaining = traceRecords.filter((r) => r.sessionKey !== sessionKey);
    if (remaining.length === 0) {
      byTrace.delete(tid);
    } else {
      byTrace.set(tid, remaining);
    }
  }

  loggerRef?.debug?.(
    `[otel:span-cache] Flushed session ${sessionKey}: ` +
    `removed ${records.length} record(s), ${traceIds.size} trace(s), ${sessionIds.size} session UUID(s)`
  );
}

// ── Internal ──────────────────────────────────────────────────────────

/**
 * Remove records that have exceeded `maxAgeMs`.
 */
function sweepStale(): void {
  if (!cacheEnabled) {
    return;
  }

  const cutoff = Date.now() - maxAgeMs;
  let removedRecords = 0;
  let removedKeys = 0;

  for (const [key, records] of bySessionKey) {
    const fresh = records.filter((r) => r.recordedAt >= cutoff);
    if (fresh.length === 0) {
      bySessionKey.delete(key);
      removedKeys++;
    } else if (fresh.length < records.length) {
      removedRecords += records.length - fresh.length;
      bySessionKey.set(key, fresh);
    }
  }

  for (const [key, records] of bySession) {
    const fresh = records.filter((r) => r.recordedAt >= cutoff);
    if (fresh.length === 0) {
      bySession.delete(key);
    } else if (fresh.length < records.length) {
      bySession.set(key, fresh);
    }
  }

  for (const [key, records] of byTrace) {
    const fresh = records.filter((r) => r.recordedAt >= cutoff);
    if (fresh.length === 0) {
      byTrace.delete(key);
    } else if (fresh.length < records.length) {
      byTrace.set(key, fresh);
    }
  }

  if (removedRecords > 0 || removedKeys > 0) {
    loggerRef?.debug?.(
      `[otel:span-cache] Stale sweep: removed ${removedRecords} record(s) from ${removedKeys} session key(s)`
    );
  }
}
