/**
 * Span Attribute Cache — lightweight in-process K-V store that captures a
 * snapshot of every span's attributes just before the span is ended.
 */

// ── Types ────────────────────────────────────────────────────────────

export type SpanAttributeValue = string | number | boolean;

/**
 * Immutable snapshot of a span's key identifiers and attributes,
 * captured just before `span.end()` is called.
 */
export interface SpanRecord {
  traceId: string;
  spanId: string;
  spanName: string;
  
  spanKind: string;
  /** openclaw.session.key — the runtime correlation key */
  sessionKey: string;
  /** session.id UUID generated by session-lifecycle.ts, if available */
  sessionId?: string;
  /** Full attribute snapshot at the moment span.end() was called */
  attributes: Record<string, SpanAttributeValue>;
  /** SpanStatusCode recorded just before span.end() — 0=UNSET, 1=OK, 2=ERROR */
  statusCode?: number;
  recordedAt: number;
  startAt?: number;
}

// ── Configuration ────────────────────────────────────────────────────

/** Records older than this are removed during periodic stale sweeps. */
const DEFAULT_MAX_AGE_MS = 30 * 60 * 1_000; // 30 minutes

/** Maximum records stored per session key (oldest are evicted first). */
const DEFAULT_MAX_RECORDS_PER_SESSION = 500;

/** How often the background stale-sweep runs. */
const DEFAULT_FLUSH_INTERVAL_MS = 60_000; // 1 minute

// ── Internal state ───────────────────────────────────────────────────

/** session UUID (from session-lifecycle) → records */
const bySession = new Map<string, SpanRecord[]>();

/** W3C traceId → records */
const byTrace = new Map<string, SpanRecord[]>();

/** openclaw.session.key (runtime key) → records */
const bySessionKey = new Map<string, SpanRecord[]>();

let flushTimer: ReturnType<typeof setInterval> | null = null;
let maxAgeMs = DEFAULT_MAX_AGE_MS;
let maxRecordsPerSession = DEFAULT_MAX_RECORDS_PER_SESSION;
let loggerRef: any = null;
let cacheEnabled = false;
let verboseLogsEnabled = false;

// ── Helpers ──────────────────────────────────────────────────────────

function appendCapped(
  map: Map<string, SpanRecord[]>,
  key: string,
  record: SpanRecord,
  cap: number
): number {
  const list = map.get(key);
  if (!list) {
    map.set(key, [record]);
    return 0;
  }

  list.push(record);
  let evicted = 0;
  if (list.length > cap) {
    // Evict oldest entries from the front
    evicted = list.length - cap;
    list.splice(0, evicted);
  }

  return evicted;
}

function formatRecord(record: SpanRecord): string {
  return `${record.spanKind}:${record.spanName}#${record.spanId.slice(0, 8)}`;
}

function formatRecordList(records: SpanRecord[]): string {
  if (records.length === 0) {
    return "empty";
  }

  return records.map((record) => formatRecord(record)).join(", ");
}

function formatLookupMap(map: Map<string, SpanRecord[]>): string {
  if (map.size === 0) {
    return "empty";
  }

  return [...map.entries()]
    .map(([key, records]) => `${key}:${records.length}[${formatRecordList(records)}]`)
    .join(" | ");
}

function countRecords(map: Map<string, SpanRecord[]>): number {
  let total = 0;
  for (const records of map.values()) {
    total += records.length;
  }
  return total;
}

function logCache(message: string): void {
  if (verboseLogsEnabled) {
    loggerRef?.info?.(message);
    return;
  }

  loggerRef?.debug?.(message);
}

function logCacheSnapshot(reason: string): void {
  logCache(
    `[otel:span-cache] Snapshot (${reason}) ` +
    `stats={sessionKeys:${bySessionKey.size}, sessions:${bySession.size}, traces:${byTrace.size}, ` +
    `sessionKeyRecords:${countRecords(bySessionKey)}, sessionRecords:${countRecords(bySession)}, traceRecords:${countRecords(byTrace)}} ` +
    `sessionKeys=[${formatLookupMap(bySessionKey)}] ` +
    `sessions=[${formatLookupMap(bySession)}] ` +
    `traces=[${formatLookupMap(byTrace)}]`
  );
}

function logRecordInsert(record: SpanRecord, evicted: { sessionKey: number; session: number; trace: number }): void {
  const sessionKeyRecords = bySessionKey.get(record.sessionKey) ?? [];
  const sessionRecords = record.sessionId ? (bySession.get(record.sessionId) ?? []) : [];
  const traceRecords = byTrace.get(record.traceId) ?? [];

  logCache(
    `[otel:span-cache] Inserted ${formatRecord(record)} ` +
    `sessionKey=${record.sessionKey} sessionId=${record.sessionId ?? "none"} traceId=${record.traceId} ` +
    `lengths={sessionKey:${sessionKeyRecords.length}, session:${sessionRecords.length}, trace:${traceRecords.length}} ` +
    `evicted={sessionKey:${evicted.sessionKey}, session:${evicted.session}, trace:${evicted.trace}}`
  );

  logCache(
    `[otel:span-cache] Lookup contents after insert ` +
    `sessionKey[${record.sessionKey}]=[${formatRecordList(sessionKeyRecords)}] ` +
    `session[${record.sessionId ?? "none"}]=[${formatRecordList(sessionRecords)}] ` +
    `trace[${record.traceId}]=[${formatRecordList(traceRecords)}]`
  );
}

// ── Public API ───────────────────────────────────────────────────────

/**
 * Start the background stale-eviction timer.
 */
export function startSpanCache(options?: {
  enabled?: boolean;
  logger?: any;
  verboseLogs?: boolean;
  maxAgeMs?: number;
  maxRecordsPerSession?: number;
  flushIntervalMs?: number;
}): void {
  if (options?.logger) loggerRef = options.logger;
  if (options?.maxAgeMs) maxAgeMs = options.maxAgeMs;
  if (options?.maxRecordsPerSession) maxRecordsPerSession = options.maxRecordsPerSession;

  cacheEnabled = options?.enabled === true;
  verboseLogsEnabled = options?.verboseLogs === true;

  if (!cacheEnabled) {
    stopSpanCache();
    logCache("[otel:span-cache] Disabled by config");
    return;
  }

  if (flushTimer) return; // already running

  const intervalMs = options?.flushIntervalMs ?? DEFAULT_FLUSH_INTERVAL_MS;
  flushTimer = setInterval(() => sweepStale(), intervalMs);

  logCache(
    `[otel:span-cache] Started (maxAge=${maxAgeMs}ms, cap=${maxRecordsPerSession}, interval=${intervalMs}ms)`
  );
  logCacheSnapshot("start");
}

/**
 * Stop the background eviction timer and clear all cached records.
 */
export function stopSpanCache(): void {
  if (cacheEnabled || bySessionKey.size > 0 || bySession.size > 0 || byTrace.size > 0) {
    logCacheSnapshot("stop.before_clear");
  }

  if (flushTimer) {
    clearInterval(flushTimer);
    flushTimer = null;
  }
  cacheEnabled = false;
  bySession.clear();
  byTrace.clear();
  bySessionKey.clear();
  logCache("[otel:span-cache] Stopped and cleared");
  verboseLogsEnabled = false;
}

/**
 * Record a span's attribute snapshot. Call this just before `span.end()`.
 *
 */
export function recordSpan(record: SpanRecord): void {
  if (!cacheEnabled) {
    logCache(
      `[otel:span-cache] Insert skipped for ${formatRecord(record)} because cache is disabled`
    );
    return;
  }

  record.startAt = record.recordedAt - getSpanDuration(record)

  const { traceId, sessionKey, sessionId } = record;

  const sessionKeyEvicted = appendCapped(bySessionKey, sessionKey, record, maxRecordsPerSession);

  let sessionEvicted = 0;
  if (sessionId) {
    sessionEvicted = appendCapped(bySession, sessionId, record, maxRecordsPerSession);
  }

  const traceEvicted = appendCapped(byTrace, traceId, record, maxRecordsPerSession);

  logRecordInsert(record, {
    sessionKey: sessionKeyEvicted,
    session: sessionEvicted,
    trace: traceEvicted,
  });
}

// ── Lookup API ───────────────────────────────────────────────────────

/**
 * Return all cached records for a given W3C trace ID.
 * Returns a snapshot copy so callers cannot mutate internal state.
 */
export function getByTrace(traceId: string): SpanRecord[] {
  return [...(byTrace.get(traceId) ?? [])];
}

/**
 * Return all cached records for a session UUID
 * (generated by session-lifecycle.ts, exposed as `session.id` on spans).
 */
export function getBySession(sessionId: string): SpanRecord[] {
  return [...(bySession.get(sessionId) ?? [])];
}

/**
 * Return all cached records for an openclaw runtime session key
 * (the correlation key that appears as `openclaw.session.key` on spans).
 */
export function getBySessionKey(sessionKey: string): SpanRecord[] {
  return [...(bySessionKey.get(sessionKey) ?? [])];
}

/**
 * Return a summary count of how many records are currently cached.
 */
export function getCacheStats(): { sessions: number; traces: number; sessionKeys: number } {
  return {
    sessions: bySession.size,
    traces: byTrace.size,
    sessionKeys: bySessionKey.size,
  };
}

// ── Flush API ─────────────────────────────────────────────────────────

/**
 * Flush (remove) all cached records for a runtime session key and its
 * associated session UUID. Call this when a session ends.
 */
export function flushBySessionKey(sessionKey: string): void {
  if (!cacheEnabled) {
    logCache(
      `[otel:span-cache] Flush skipped for session ${sessionKey}: cache is disabled`
    );
    return;
  }

  const records = bySessionKey.get(sessionKey);
  if (!records) {
    logCache(
      `[otel:span-cache] Flush skipped for session ${sessionKey}: no cached entries`
    );
    return;
  }

  // Collect trace IDs and session UUIDs touched by this session so we
  // can prune those indices too.
  const traceIds = new Set<string>();
  const sessionIds = new Set<string>();

  for (const r of records) {
    traceIds.add(r.traceId);
    if (r.sessionId) sessionIds.add(r.sessionId);
  }

  bySessionKey.delete(sessionKey);

  for (const sid of sessionIds) {
    bySession.delete(sid);
  }

  // Only remove trace entries that belong exclusively to this session.
  // A trace may span multiple session keys (e.g. spawned subagent inherits
  // the parent trace), so we check each record before removing.
  for (const tid of traceIds) {
    const traceRecords = byTrace.get(tid);
    if (!traceRecords) continue;
    const remaining = traceRecords.filter((r) => r.sessionKey !== sessionKey);
    if (remaining.length === 0) {
      byTrace.delete(tid);
    } else {
      byTrace.set(tid, remaining);
    }
  }

  logCache(
    `[otel:span-cache] Flushed session ${sessionKey}: ` +
    `removed ${records.length} record(s), ${traceIds.size} trace(s), ${sessionIds.size} session UUID(s)`
  );
  logCacheSnapshot(`flush:${sessionKey}`);
}

// ── Internal ──────────────────────────────────────────────────────────

/**
 * Remove records that have exceeded `maxAgeMs`.
 */
function sweepStale(): void {
  if (!cacheEnabled) {
    return;
  }

  const cutoff = Date.now() - maxAgeMs;
  let removedRecords = 0;
  let removedKeys = 0;

  for (const [key, records] of bySessionKey) {
    const fresh = records.filter((r) => r.recordedAt >= cutoff);
    if (fresh.length === 0) {
      bySessionKey.delete(key);
      removedKeys++;
    } else if (fresh.length < records.length) {
      removedRecords += records.length - fresh.length;
      bySessionKey.set(key, fresh);
    }
  }

  for (const [key, records] of bySession) {
    const fresh = records.filter((r) => r.recordedAt >= cutoff);
    if (fresh.length === 0) {
      bySession.delete(key);
    } else if (fresh.length < records.length) {
      bySession.set(key, fresh);
    }
  }

  for (const [key, records] of byTrace) {
    const fresh = records.filter((r) => r.recordedAt >= cutoff);
    if (fresh.length === 0) {
      byTrace.delete(key);
    } else if (fresh.length < records.length) {
      byTrace.set(key, fresh);
    }
  }

  if (removedRecords > 0 || removedKeys > 0) {
    logCache(
      `[otel:span-cache] Stale sweep: removed ${removedRecords} record(s) from ${removedKeys} session key(s)`
    );
  } else {
    logCache("[otel:span-cache] Stale sweep: no entries flushed");
  }

  logCacheSnapshot("maintenance.1m");
}


/**
 * Returns the first timestamp available for a given session UUID * 
 */
export function getSessionStartTime(sessionId: string): number | null {
  const records = bySession.get(sessionId);
  //returning the earliest startAt timestamp available for the session
  if (!records || records.length === 0) {
    return null;
  }

  return records.reduce((earliest, record) => {    const recordStart = record.startAt ?? record.recordedAt;
    return recordStart < earliest ? recordStart : earliest;
  }, records[0].startAt ?? records[0].recordedAt);

  //// Assuming records are added in chronological order, the first record's timestamp is the start time
  //console.log(`DEBUG getSessionStartTime for session ${sessionId}: first record at ${records[0].recordedAt}, duration=${getSpanDuration(records[0])}ms`);
  //return records[0].recordedAt - getSpanDuration(records[0]);
}

/**
 * Returns the last timestamp available for a given session UUID * 
 */
export function getSessionEndTime(sessionId: string): number | null {
  const records = bySession.get(sessionId);
  //returning the latest endAt timestamp available for the session
  if (!records || records.length === 0) {
    return null;
  }

  return records.reduce((latest, record) => {    const recordEnd = record.recordedAt;
    return recordEnd > latest ? recordEnd : latest;
  }, records[0].recordedAt);
}

/**
 * Returns all the span records for a given session UUID and span type (spanName)
 */
export function getSpansByType(spanName: string, startTime?: number, endTime?: number, sessionId?: string): SpanRecord[] {
  let records: SpanRecord[] = [];
  if (sessionId){
    records = bySession.get(sessionId) ?? [];
    if (!records) {
      return [];
    }
  } else if (startTime && endTime) { //Note: this assumes that all sessions are related to the main one. This is a strong assumption which means that all the sessions related to top-level agents are related to the current session
    // get all the records with startAt >= startTime and recordedAt <= endTime
    for (const sessionRecords of bySession.values()) {
      for (const record of sessionRecords) {
        const recordStart = record.startAt ?? record.recordedAt;
        if (recordStart >= startTime && record.recordedAt <= endTime) {
          records.push(record);
        }
      }
    }
  } else{
    loggerRef.warn?.(`[otel:span-cache] getSpansByType called with insufficient parameters: spanName=${spanName} sessionId=${sessionId} startTime=${startTime} endTime=${endTime}`);
    return [];
  }

  console.log(`DEBUG filtering for name ${spanName} in session ${sessionId}`);
  for (const r of records.filter(record => record.spanName === spanName)) {
    console.log(`DEBUG getSpansByType: record ${formatRecord(r)} with spanName ${r.spanName} and sessionId ${r.sessionId}`);
  }
  return records.filter(record => record.spanName === spanName);
}


/**
 * Returns the duration of a given span record in milliseconds.
 */
function getSpanDuration(record: SpanRecord): number {
  // Depending on the span type, duration attribute changes
  const keys = [
    "otel.span.duration_ms",
    "openclaw.request.duration_ms",
    "openclaw.agent.duration_ms",
    "openclaw.tool.duration_ms"
  ];
  console.log(`DEBUG getSpanDuration for record ${formatRecord(record)}: checking keys ${keys.join(", ")}`);
  for (const key of keys) {
    const duration = record.attributes[key];
    if (typeof duration === "number") {
      return duration;
    }
  }
  return -1;
}